### ISSUE TITLE
Does not build out of the box

### ISSUE THREAD

**Issue by lmdodd** [cms-analysis/HiggsAnalysis-HiggsToTauTau#628]
I was not able to build CombineHarvester out of the box. The GitVersion information had to be removed from CombineHarvester/CombineTools/src/CombineHarvester_Datacards.cc on line 26 and line 452. The .h file seems to be missing.

Laura

**Comment by ajgilbert** [comment]
Hi Laura, thanks for the report - let me look into this today and let you know. Can I just check which cmssw release you are using and which branch of this package? The GitVersion file is supposed to be created automatically when you run make but clearly something is going wrong. cheers, Andrew

**Comment by lmdodd** [comment]
Hi Andrew,

I followed the instructions http://cms-analysis.github.io/HiggsAnalysis-HiggsToTauTau/
except for the


export SCRAM_ARCH=slc6_amd64_gcc481

Let me try reinstalling with setting the architecture, and I will get back to you. :)

Best,
Laura

On May 22, 2015, at 9:33 AM, Andrew Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Laura, thanks for the report - let me look into this today and let you know. Can I just check which cmssw release you are using and which branch of this package? The GitVersion file is supposed to be created automatically when you run make but clearly something is going wrong. cheers, Andrew

**Comment by lmdodd** [comment]
I still get the same error when I export the architecture.
Laura

On May 22, 2015, at 1:17 PM, Laura Margaret Dodd <ldodd@cern.ch<mailto:ldodd@cern.ch>> wrote:

Hi Andrew,

I followed the instructions http://cms-analysis.github.io/HiggsAnalysis-HiggsToTauTau/
except for the


export SCRAM_ARCH=slc6_amd64_gcc481

Let me try reinstalling with setting the architecture, and I will get back to you. :)

Best,
Laura

On May 22, 2015, at 9:33 AM, Andrew Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Laura, thanks for the report - let me look into this today and let you know. Can I just check which cmssw release you are using and which branch of this package? The GitVersion file is supposed to be created automatically when you run make but clearly something is going wrong. cheers, Andrew

**Comment by ajgilbert** [comment]
Ok I think I've fixed it (cb5130b24cbdd846c6e216f170da3a04d44860c8). If you update the master branch, then do:

    make clean_all; make all 

hopefully it will work now.

**Comment by lmdodd** [comment]
It works. :)
Thank you, Andrew!

On May 22, 2015, at 2:05 PM, Andrew Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I think I've fixed it (cb5130b<https://github.com/cms-analysis/HiggsAnalysis-HiggsToTauTau/commit/cb5130b24cbdd846c6e216f170da3a04d44860c8>). If you update the master branch, then do:

make clean_all; make all


hopefully it will work now.
